### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [blas-lapack-rs/blas-src#11]
It would be great if there was some example of usage. Perhaps a project with a basic operation with `cargo run` with any actions required outside of `cargo run` specified.

**Comment by astraw** [comment]
Does this help: https://crates.io/crates/blas-src/reverse_dependencies ?

**Comment by Tastaturtaste** [comment]
I tried understanding how this crate is supposed to work, but I don't get it. 
blas-src does not have anything in its public interface. Its dependencies like openblas-src also don't have any public interface.
I tried looking at blas-srcs dependents. They specify it in their cargo.toml, but they never `use` something from this crate. How would they even,  there is no public api. 

I would really appreciate some pointers on what this provides and how it does that.

**Comment by jedbrown** [comment]
You probably want [blas](https://lib.rs/crates/blas) rather than `blas-src`, which just exists to coordinate multiple implementations of the Fortran interface.

**Comment by jedbrown** [comment]
This explains how the whole system fits together. https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki

**Comment by IvanUkhov** [comment]
I hope Jed’s answers (thank you!) cover it.
