### ISSUE TITLE
New source of blas + lapack (from R) available

### ISSUE THREAD

**Issue by bnaras** [blas-lapack-rs/blas-src#14]
I have created a new source of BLAS that is sometimes needed for for building new R packages that use Rust plus BLAS and LAPACK. For example, see: [R package clarabel](https://cran.r-project.org/package=clarabel) and the underlying Rust package [Clarabel](https://github.com/oxfordcontrol/Clarabel.rs) which requires BLAS and LAPACK to link against.  It makes sense to make this available under your [blas-lapack-rs](https://github.com/blas-lapack-rs) umbrella, rather than my personal repo before I publish the crate.  Would you agree? Let me know.

Here's the link: https://github.com/bnaras/r-blas-lapack-src

**Comment by astraw** [comment]
@bnaras This makes sense to me. Thanks for the suggestion. If this also makes sense to @IvanUkhov, the next step would be to go into the github settings for https://github.com/bnaras/r-blas-lapack-src and go to "transfer ownership".

@IvanUkhov it looks like you are the only one with any owner or admin rights in the blas-lapack-rs organization https://github.com/orgs/blas-lapack-rs/people , making the bus factor uncomfortably low. Would you consider adding someone as an admin? I would volunteer myself. Also, it would be perfectly fine (preferred even!) if it is someone else.

**Comment by bnaras** [comment]
@astraw Thanks.  I am happy to transfer the ownership if @IvanUkhov agrees and can continue to maintain this crate.

**Comment by IvanUkhov** [comment]
Andrew, yes, it makes sense to have more. I have added you and @termoshtt, who is probably the most active contributor currently, as owners.

Balasubramanian, I have added you to the [Sources](https://github.com/orgs/blas-lapack-rs/teams/sources/members) team, whose access is constrained to source crates.

I would also think a little bit about the name. Perhaps `r-src` sounds a bit too broad at first glance, but `accelerate-src` does so too. Plus it will be always considered in the scope of this ecosystem. Or maybe the one in R has a proper name?

**Comment by bnaras** [comment]
@IvanUkhov Thanks. I too wasn't happy about my original name and `r-src` sounds fine to me.  I'll make the changes.

**Comment by IvanUkhov** [comment]
Thank you for transferring the repository, Balasubramanian! I have added it to the Sources team, which has the Maintain role for all repositories included. Please confirm that you have write access.

One can now update the Architecture page and also add it to `blas-src` and `lapack-src`.

**Comment by bnaras** [comment]
@IvanUkhov I updated the build yaml to rerun the tests and strangely it runs fine on MacOS accelerate, but fails on other things. However, it did run fine on Ubuntu latest. I will keep tweaking this to see if I can get it to go.

Also, I assume I need to bump the version to publish to crates.io. Shall I use 0.9 for both this and lapack-src?

**Comment by IvanUkhov** [comment]
It would be nice to fix those small things I commented on, and it would be good to recover the CI. I commented on that in the PR. It should work. Then one can indeed publish a new version.

**Comment by bnaras** [comment]
Oh! Those were [addressed right away](https://github.com/blas-lapack-rs/blas-src/commit/a885fc748a7f417968a8693538426e2f2dac1f1c) (thanks), unless I missed something . The only thing that is now stopping things is the CI failing.

**Comment by IvanUkhov** [comment]
It can be considered solved now. Thank you!
